### ISSUE TITLE
Bug SugarCubes ?

### ISSUE THREAD

**Issue by cl4cnam** [cl4cnam/simulPersonne#1]
Dans la **_branche testBug1Hub_**
Avec ce code :
```javascript
	SC.repeat(SC.forever,
		SC.par(
			SC.actionOn(evt, SC.nothing()),
			SC.act(()=>console.log('instant : ', m.instantNumber))
		)
	)
```
l'action ne se produit que tous les deux instants.

J'ai mis un SugarCubes.js simplifié (et j'ai ajouté des console.log) pour essayer de comprendre ce qu'il se passe.

**Comment by LordManta** [comment]
Bonjour,

C’est normal, SugarCubesJS a une sémantique légèrement différente de celle de SugarCubes v5 : SC.repeat(… p) déroule systématiquement p en mettant un pause en séquence:

repeat p end -> p';pause; repeat p end

Comme actionOn consomme déjà un instant, avec le repeat on en consomme 2 d’où une exécution un instant sur 2.

Pour écrire le même programme en 1 instant il faudrait écrire :

SC.par(
  SC.actionOn(evt, SC.NO_FUN, undefined, SC.forever)
  , SC.action(()=>console.log('instant : ', m.instantNumber, SC.forever)
)

Donc non ce n’est pas un bug mais un changement de sémantique.

—
Jean-Ferdy

**Comment by cl4cnam** [comment]
Merci :)
